// <auto-generated />
namespace ReportAnIssue.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AttachmentsRemoveIssueId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttachmentsRemoveIssueId));
        
        string IMigrationMetadata.Id
        {
            get { return "201801101406317_Attachments-RemoveIssueId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
